version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      python:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      docs:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
